- text/file_test.go
- text/samples/benchmark3.perf
- text/samples/benchmark4.perf
- text/unit_test.go
This commit adds a more heavy benchmark to TextUnits
`cd text/ && go test -bench=`
Add more extensive tests and benchmarks for heavy TextUnits
> feat(benchmarks): Add more extensive tests and benchmarks for heavy TextUnits

- text/file.go
- text/file_test.go
> Fixing wrong column when finding is in the first lin

- renovate.json
> renovate: scheduling renovatebot to run every weekend

- renovate.json
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>
> renovate: add signed of by on commit body message

- .github/workflows/coverage.yml
- .github/workflows/license.yaml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> ci: bump Go 1.17 on all workflows

- platforms/android/manifest_test.go
- text/reader.go
- text/reader_test.go
- text/reader_win.go
> all: replace ioutil deprecated package usages

- BUILD.md
Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>
Review of content and add the BUILD.md on the repo
Check BUILD.md file on the root project.
Addition of the BUILD.md file on the Horusec repos
> docs:add build markdwon file

- README.md
> readme:chore - updating readme to the new engine format

- go.mod
- go.sum
- internal/ast/ast.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/classes.js
- internal/horusec-javascript/testdata/source/expressions.js
- internal/horusec-javascript/testdata/source/functions.js
- internal/horusec-javascript/testdata/source/imports.js
- internal/horusec-javascript/testdata/source/statements.js
- internal/horusec-javascript/testdata/source/var_declarations.js
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>
> semantic: add while statement

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/statements.js
> semantic/javascript:feature - adding switch statement

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/statements.js
> semantic/javascript:feature - adding for and for in statements

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/statements.js
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>
> semantic:chore - add continue,labeled and identifier statement

- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/statements.js
Since export statements will not be very useful information
in our ast for now, we will ignore this statement.
> semantic/javascript:feature - add export statement

- rule.go
The new fields added are:
CWEs, CVEs, Mitigation, Reference, SafeExample, UnsafeExample.
Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>
> rule:feature - Add new fields in Metadata in regex rules

- internal/ast/walk.go
> ast:fix - missing node cases on Walk

- internal/ir/builder.go
- internal/ir/create.go
- internal/ir/ir.go
- internal/ir/print.go
- internal/testdata/expected/javascript/ir/comments.js.out
- internal/testdata/expected/javascript/ir/expressions.js.out
- internal/testdata/expected/javascript/ir/functions.js.out
- internal/testdata/expected/javascript/ir/statements.js.out
This commit introduce a SSA based IR to semantic engine. The SSA
construction algorithm is based on the algorithm described on paper
Simple and Efficient Construction of Static Single Assignment Form.
Basically when parsing a variable declaration on AST, we store this
variable on current basic block of the function that the variable was
defined, when we need to lookup this variable we first check if the
current block contains the declared variable, if not exists we
recursively search on the predecessors blocks of the current basic block
and create a phi node with all possible values that this variable can
have.
The paper describe algorithms for optimizations but this commit only
implement the basic idea of store variables on basic block that defines
it and how we create phi nodes for …
> ir:feat - SSA based IR

- semantic/analysis/value/value.go
> analysis/value:feat - analyze phi values edges

- semantic/analysis/value/value.go
- semantic/analysis/value/value_test.go
> analysis/value:feat - analyze Phi and Object values

- semantic/analysis/value/value.go
- semantic/analysis/value/value_test.go
> analysis/value:feat - support key value rules

- internal/ir/builder.go
> ir:chore - remove fixed TODO

- internal/ir/builder.go
> ir:chore - fix outdated Function.emit godoc

- SECURITY.md
This pull request adds the SECURITY Policies documentation.
> docs:feat - Security Policies
