ZupIT/horusec-engine

- .github/workflows/coverage.yml
- .github/workflows/dco.yaml
- .github/workflows/license.yaml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/test.yml
This commit change the workflows to run only on pull requests instead on
push. With this change pull requests from contributors outside the ZupIT
organization will run.
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>
> workflows: add permissions and triggering "on pull request"

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/horusec-javascript/testdata/expected/statements.js.out
- internal/horusec-javascript/testdata/source/statements.js
Added try stament type to the genetic ast, walk validation to
the try statement and a parser for the javascript tree sitter
ast to the generic ast.
> semantic/javascript:feature - adding try statement

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/testdata/expected/imports.js.out
- internal/horusec-javascript/testdata/source/imports.js
Previously when a import statement is declared using an alias, this
alias name was being ignored by AST. This commit add a new field Alias
on ImportDecl struct node to store this alias name if exists.
The test cases of import statement was also change to more easily
reading, avoiding generic and duplicate import names like foo, bar. 
> ast,javascript:chore - add alias identifier on ImportDecl

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/testdata/expected/javascript/ast/comments-2.js.out
- internal/testdata/expected/javascript/ast/comments.js.out
- internal/testdata/source/javascript/comments-2.js
- internal/testdata/source/javascript/comments.js
This commit introduce support to ignore block of codes using #nosec
comments.
The nosec directive can be used in any code block, the only requirement is
that the comment must be on the top line of the code that should be ignored,
comments on the same or below or more than one line above are not supported.
To view supported syntaxes see test file
internal/testdata/source/javascript/comments.js.
> javascript/ast:feat - add support to #nosec directives

- internal/ir/builder.go
- internal/ir/create.go
- internal/ir/ir.go
- internal/testdata/expected/javascript/ast/expressions.js.out
- internal/testdata/expected/javascript/ir/expressions.js.out
- internal/testdata/source/javascript/expressions.js
Previously any expression that was not inside a function was ignored. This
pull request adds support for these expressions, where a temporary
function will be created and all expressions in the file will be parsed
through it.
> ir:feature - support expressions outside of functions 

- internal/ir/builder.go
- internal/testdata/expected/javascript/ast/functions.js.out
- internal/testdata/expected/javascript/ir/functions.js.out
- internal/testdata/source/javascript/functions.js
Previously we was supporting ast.SelectorExpr only if the Expr field was
a identifier, so this commit improve this support handling the Expr
field recursively and resolving identifier imports.
Now we support expressions like `a.b.c()` and `a.b().c.d()`. For
selector expressions that Expr could be a call expression, temp
variables will be created and these temp variable will be used on the
name of selector expression.
Example:
const a = a.b(10).c.d(20)
IR:
%t0 = a.b(10)
%t1 = %t0.c.d(20)
This apply not only for call expression but any expression on
ast.SelectorExpr.Expr that is not an *ast.Ident or *ast.SelectorExpr.
The *ast.SelectorExpr is also resolved when assigning variable values, but
we still need to improve this. When assigning a variable with a selector
expression, a new variable …
> ir:feat - improve support of ast.SelectorExpr

- internal/horusec-javascript/ast.go
- internal/testdata/expected/javascript/ast/functions.js.out
- internal/testdata/expected/javascript/ir/functions.js.out
- internal/testdata/source/javascript/functions.js
Previously variable declarations with var inside functions were not
supported by AST. This pull request adds this support to the AST.
> ast:chore - support var decl inside functions

- internal/ir/builder.go
- internal/ir/ir.go
- internal/ir/print.go
- internal/testdata/expected/javascript/ir/statements.js.out
This commit add support to represent if statements on IR. This
representation is using Control-flow graph[1].
To add this support some new structs was created:
- If: Represents the if statement instruction. Contains the condition
value of if and a basic block.
- Jump: Represents a jump instruction. This jump is used to represents
jumps on if statement, for example, a jump from if them to if done or
if else to if done. This jump instruction will also be used in other
instructions that are represented using CFG's.
This commit add the ir/statements.js.out file that contains the if
statements IR code generated. Since we don't support all statements from
this test yet, this file was rewrited  using the debug flag disabled, so
the statements that we don't support is represented as empty blocks. …
> ir:feat - add support for if statements

- internal/ir/builder.go
- internal/testdata/expected/javascript/ast/functions.js.out
- internal/testdata/expected/javascript/ir/functions.js.out
- internal/testdata/source/javascript/functions.js
Previously when using global values in functions, the value
was not being parsed. This commit changes this behavior to check and
parse the value of the global variable and add to the function's locals.
> ir:bugfix - fixing lookup for global values

- internal/horusec-javascript/ast.go
Previously if we try to parse a return without any statement we had a
nil pointer panic. This commit add a simple validation to check if the
return has statement, if it has, parse it, otherwise return a
ast.ReturnStmt without any results.
> javascript/ast:fix - panic when parsing return without stmt

- internal/ast/ast.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/ir/builder.go
- internal/ir/ir.go
- internal/testdata/expected/javascript/ast/expressions.js.out
- internal/testdata/expected/javascript/ast/statements.js.out
- internal/testdata/expected/javascript/ir/expressions.js.out
- internal/testdata/expected/javascript/ir/statements.js.out
- internal/testdata/source/javascript/expressions.js
- internal/testdata/source/javascript/statements.js
This commit add support for for loop's on IR.
Initially to add this support some bugs was fixed on parse from
tree-sitter CST to generic AST; Previously we was parsing the for
statement condition as a statement, which always result in a
ast.ExprStmt, so the Cond was changed to store the expression directly
which facilitated the parse in the IR. The increment node on for loop
could be nil in some syntaxes, or a empty_statement, so this commit also
handle these cases. A new field Op was also added on ast.IncExpr to
store the operator of a increment expression (++ or --).
On IR this commit add support for for loop's and increment expression
(since increment expressions is almost always used on for loop's). The
increment expression is converted to a binary expression, so a++ is
converted to a …
> ir:feat - add support for for loop

- internal/horusec-javascript/ast.go
- internal/testdata/expected/javascript/ast/var_declarations.js.out
- internal/testdata/expected/javascript/ir/var_declarations.js.out
- internal/testdata/source/javascript/var_declarations.js
Previously the new_expression handle parser was always expecting that
the parent node was a variable declaration, witch it's not true because
we can have a code like this: foo(new Bar()).
This commit fix this issue by setting the ast.ObjectExpr.Name field only
if the parent node of new_expression is a variable_declarator.
> javascript/ast:fix - new expression outside var decl

- internal/utils/testutil/analysis.go
- semantic/analysis/call/call_test.go
- semantic/analysis/value/value_test.go
This commit introduce some new test cases for analysis/call and
analysis/value packages. This commit also change the testutil package to
handle struct declarations when executing the tests.
> analysis:chore - add new testcases

- internal/ir/builder.go
- internal/testdata/expected/javascript/ast/functions.js.out
- internal/testdata/expected/javascript/ir/expressions.js.out
- internal/testdata/expected/javascript/ir/functions.js.out
- internal/testdata/source/javascript/functions.js
Previously if we define a new variable and call a method or use a field
from this create variable the method builder.selectorExpr was not
lookuping the correct name for this variable, example:
Source:
```
let a = new A()
a.doSomething()
```
IR:
```
%t0 = constructor(A)
%t1 = a.doSomething()
```
This commit fix this issue by adding a new else if on builder.selectorExpr
to try to lookup the identifier name, and if the variable exists, use
their name instead the name of identifier, with this, the following
correctly IR is generated:
```
%t0 = constructor(A)
%t1 = %t0.doSomething()
```
> ir:fix - invalid selector expr when using declared variable

- internal/utils/testutil/analysis.go
- semantic/analysis/call/call_test.go
- semantic/rule.go
Previously we was not analysis anonymous function, this commit fix this
issue by analysis the parent function and all anonymous functions
declared inside it.
> analysis:fix - analyze anonymous function

- internal/ir/builder.go
- internal/ir/create.go
- internal/ir/ir.go
- internal/testdata/expected/javascript/ir/functions.js.out
- semantic/analysis/call/call_test.go
Previously our parsing strategy of *ast.SelectorExpr was very simple, we
basically created a variable whose name was the concatenation of
ast.SelectorExpr.Expr and ast.SelectorExpr.Sel. Although this approach
works well, it's very simple and doesn't allow us to write rules that
look for method calls on specific objects.
Suppose we need to write a rule for a method call on an object Foo:
```
let foo = new Foo()
foo.something()
```
The code above was generating the following IR:
```
%t0 = constructor(Foo)
%t1 = %t0.something()
```
As mentioned above, the selector expression that holds foo variable and
something function call was resulting in a function call witch
%t0.something as your name (since the %t0 is the variable that holds the
Foo instance). This approach is pretty bad because we …
> ir:feat - better approach to parse *ast.SelectorExpr

- internal/ir/builder.go
- internal/ir/print.go
- internal/testdata/expected/javascript/ast/statements.js.out
- internal/testdata/expected/javascript/ir/statements.js.out
- internal/testdata/source/javascript/statements.js
This commit add support to while statements on IR. This support follow
the same idea of for loop, we have a while.body, while.cond and
while.done blocks, the while.cond decide where to jump according to
condition, if true goto while.body, otherwise goto while.done,
while.body always jump to while.cond at the end to represent the loop.
Note: This implementation is not fully complete, in the future we should
have a better support for incomplete basic blocks (in this case the
while.cond is a incomplete block because the while.body is added as a
predecessor after the code on while.cod is emitted). This implementation
works well for what we need now, we just won't be able to correctly represent
a variable mutation inside the while.body that is used as a condition in
while.cond. In the future …
> ir:feat - add support for while statements

- internal/ir/builder.go
- internal/testdata/expected/javascript/ast/statements.js.out
- internal/testdata/expected/javascript/ir/statements.js.out
- internal/testdata/source/javascript/statements.js
This commit adds support for the switch statement parse to its
IR.
> feature:IR - adding the switch statement parse

- internal/ast/ast.go
- internal/horusec-javascript/ast.go
- internal/horusec-javascript/node_types.go
- internal/ir/builder.go
- internal/ir/ir.go
- internal/testdata/expected/javascript/ast/expressions.js.out
- internal/testdata/expected/javascript/ir/expressions.js.out
- internal/testdata/source/javascript/expressions.js
This commit adds support in both AST and IR for parsing the subscript
node expr.
> semantic:feature - adding the AST and IR subscript expr node

- internal/ast/ast.go
- internal/ast/walk.go
- internal/horusec-javascript/ast.go
- internal/ir/builder.go
- internal/ir/create.go
- internal/ir/ir.go
- internal/testdata/expected/javascript/ast/statements.js.out
- internal/testdata/expected/javascript/ir/statements.js.out
- internal/testdata/source/javascript/statements.js
This commit add support for labeled statements (for/while/switch).
To add this support a new struct `lblock` was created to store the
blocks that is used to jump when parsing for/while/switch statements
body. A stack is created to store these blocks when processing the
statements, basically, when entering a for/while/switch stmt we push a
new target and after the processing the stmt body we pop the target and
we processing an `break` or `continue` we just get the head of stack to
jump it. A map of labeled blocks was also implemented to store blocks
that are labeled, so if a block has a label we get the block to jump
from this map, otherwise we get the head of stack to jump it.
This commit also improve the generated AST for labeled statements,
instead of store a list of []ast.Stmt we just …
> ir:feat: add support for labeled statements

- engine.go
- engine_test.go
Signed-off-by: guilhermepaulozup <guilherme.paulo@zup.com.br>
Added a call to _os.PathSeparator_ to _isFileFromGitFolder_ to form a _.git/_ path.
This way the engine can properly differentiate between the .git/ directory and .github/ directory (used in Github Actions) files.
Running ```horusec start --log-level="debug"``` should properly read the files in .github/workflows/ folder.
Changed _isFileFromGitFolder_ to include on the return: ```".git"+string(os.PathSeparator)```
> [engine][bugfix]: Fixed bug where Horusec couldn't properly differentiate between .git/ and .github/ path
